{
 "title": "Counter_Director",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "GET_GENRE_BY_ID",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "GET_GENRE_BY_ID_seconds_max" }
   ]
  },
  {
   "title": "Counter_Variables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "FIRST_COUNTER" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "GET_ALL_GENRES_seconds_count" }
   ]
  },
  {
   "title": "Counter_Director",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "BINDER_COUNTER_total" }
   ]
  }
 ]
}